config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"
  resources :users, only: [:show, :update]
  resources :items do
    collection do
      get 'search'
    end
  end
  resources :items do
    resources :orders, only: [:index, :create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :university
  belongs_to :department
  has_many :items
  has_many :orders

  with_options presence: true do
    validates :nickname
    validates :birthday

    with_options numericality: { other_than: 1, message: "を選択してください" } do
      validates :university_id
      validates :department_id
    end
  end
  
  PASSWORD_REGEX = /\A(?=.*[a-zA-Z])(?=.*?\d)[a-zA-Z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'は半角英字と半角数字の両方を含めて設定してください'
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @items = @user.items
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<header class='top-page-header'>
  <div class="left-contents">
    <ul class="left-list">
      <li><%= link_to image_tag("secondhands-logo.png", class: "secondhands-icon"), "/" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn-square" %></li>
      <li><%= link_to '商品一覧へ', root_path, class: "btn-square" %></li>
   </ul>
  </div>
  <div class="right-contents">
    <div class="right-list">
      <%= link_to current_user.nickname + " さんのマイページ", "#", class: "user-nickname" %>
    </div>
  </div>
</header>

<div class='mypage-main'>
  <% if @items[0] != nil %>
    <div class='on-sale-item-title'>販売中商品</div>
    <% @items.each do |item| %>
      <% if item.order.blank?%>
        <div class="on-sale-item-lists">
          <div class="on-sale-item-left">
            <%=link_to item_path(item.id),class: 'on-sale-item-img-content' do %>
              <%= image_tag item.image, class: "on-sale-item-img" %>
            <%end%>
            <div class='on-sale-item-info'>
              <div class='on-sale-item-name-price'>
                <br><%= item.name %>
                <br><%= item.price.to_s(:delimited) %>円
              </div>
              <div class='on-sale-item-info-sub'>
                <br><%= item.year_period.name %>
                <br><%= item.lecture %>
                <br><%= item.teacher %>
              </div>
            </div>
          </div>
          <div class="on-sale-item-right">
            <%= link_to '編集', edit_item_path(item.id), method: :get, class: "on-sale-item-edit-btn" %>
            <%= link_to "削除", item_path(item.id), method: :delete, class:"on-sale-item-destroy-btn" %>
            <%= link_to "詳細", item_path(item.id), class:"on-sale-item-show-btn" %>
          </div>
        </div>
      <%end%>
    <%end%>
    
    <div class='on-sale-item-title'>売却済み商品</div>
    <% @items.each do |item| %>
      <% if item.order.present?%>
        <div class="on-sale-item-lists">
          <div class="on-sale-item-left">
            <%=link_to item_path(item.id),class: 'on-sale-item-img-content' do %>
              <%= image_tag item.image, class: "on-sale-item-img" %>
            <%end%>
            <div class='on-sale-item-info'>
              <div class='on-sale-item-name-price'>
                <br><%= item.name %>
                <br><%= item.price.to_s(:delimited) %>円
              </div>
              <div class='on-sale-item-info-sub'>
                <br><%= item.year_period.name %>
                <br><%= item.lecture %>
                <br><%= item.teacher %>
              </div>
            </div>
          </div>
          <div class="on-sale-item-right">
            <%= link_to "詳細", item_path(item.id), class:"on-sale-item-show-btn" %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <div class='no-message'>
      現在出品中の商品はありません
    </div>
  <% end %>
</div>

<%# 出品ボタン %>
<%= link_to(new_item_path, class: 'purchase-btn') do %>
  出品する
<% end %>
<%# /出品ボタン %>

<%= render "shared/footer" %>