config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"
  resources :users, only: [:show, :update]
  resources :items do
    collection do
      get 'search'
    end
  end
  resources :items do
    resources :orders, only: [:index, :create]
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :year_period
  belongs_to :sales_status
  belongs_to :scheduled_delivery
  belongs_to :user
  has_one_attached :image
  has_one :order

  with_options presence: true do
    validates :image
    validates :name

    with_options numericality: { greater_than: 0,allow_blank: true }, format: { with: /\A[0-9]+\z/,allow_blank: true } do
      validates :price
    end

    with_options format: { with: /\A[ぁ-んァ-ン一-龥０-９]+\z/, allow_blank: true } do
      validates :lecture
      validates :teacher
      validates :author
      validates :publisher
    end

    with_options numericality: { other_than: 1, message: "を選択してください"} do
      validates :year_period_id
      validates :sales_status_id
      validates :scheduled_delivery_id
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :set_q, only: [:index, :search]
  before_action :move_to_index, except: [:index, :search, :new, :create]
  before_action :move_to_top, only: [:edit, :update, :destroy]
  before_action :contributor_confirmation, only: [:edit, :update, :destroy]

  def index
    @items = Item.order('created_at DESC')
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path
    else
      render :edit
    end
  end

  def destroy
    redirect_to root_path if @item.destroy
  end

  def search
    @results = @q.result.order('created_at DESC')
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :year_period_id, :lecture, :teacher, :sales_status_id, :scheduled_delivery_id, :author, :publisher, :image).merge(user_id: current_user.id)
  end

  def set_q
    @q = Item.ransack(params[:q])
  end

  def move_to_index
    @item = Item.find(params[:id])
  end

  def move_to_top
    redirect_to root_path unless @item.order.blank?
  end

  def contributor_confirmation
    redirect_to root_path unless current_user.id == @item.user_id
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('secondhands-logo.png', size: '180x70'), "/" %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品情報を入力</h2>
    <%= form_with model: @item, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
      <%# 商品画像 %>
      <div class="img-upload">
        <div class="weight-bold-text">
          商品画像
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id:"image"%>
        </div>
      </div>
      <%# /商品画像 %>
      <%# 商品名 %>
      <div class="new-items">
        <div class="weight-bold-text">
          商品名
          <span class="indispensable">必須</span>
        </div>
        <%=f.text_area :name, class:"item-text", id:"item-name", placeholder:"商品名を入力" %>
      </div>
      <%# /商品名 %>
      <%# 商品価格 %>
      <div class="sell-price">
        <div class="weight-bold-text">
          商品価格
          <span class="indispensable">必須</span>
          <p>※送料は出品者負担になります</p>
        </div>
        <div class="price-space">
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"半角数字で入力" %>
        </div>
      </div>
      <%# /商品価格 %>
      <%# 年度・受講期 %>
      <div class="new-items">
        <div class="weight-bold-text">
          年度・受講期
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:year_period_id, YearPeriod.all, :id, :name, {}, {class:"active-select", id:"item-year-period"}) %>
      </div>
      <%# /年度・受講期 %>
      <%# 講義名 %>
      <div class="new-items">
        <div class="weight-bold-text">
          講義名
          <span class="indispensable">必須</span>
        </div>
        <%=f.text_area :lecture, class:"item-text", id:"item-lecture", placeholder:"講義名を入力（全角）" %>
      </div>
      <%# /講義名 %>
      <%# 先生名 %>
      <div class="new-items">
        <div class="weight-bold-text">
          先生名
          <span class="indispensable">必須</span>
        </div>
        <%=f.text_area :teacher, class:"item-text", id:"item-teacher", placeholder:"先生の氏名を入力（全角）" %>
      </div>
      <%# /先生名 %>
      <%# 商品の状態 %>
      <div class="new-items">
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:sales_status_id, SalesStatus.all, :id, :name, {}, {class:"active-select", id:"item-seles-status"}) %>
      </div>
      <%# /商品の状態 %>
      <%# 発送までの日数 %>
      <div class="new-items">
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:scheduled_delivery_id, ScheduledDelivery.all, :id, :name, {}, {class:"active-select", id:"item-scheduled-delivery"}) %>
      </div>
      <%# /発送までの日数 %>
      <%# 著者名 %>
      <div class="new-items">
        <div class="weight-bold-text">
          著者名
          <span class="indispensable">必須</span>
        </div>
        <%=f.text_area :author, class:"item-text", id:"item-autor", placeholder:"著者名を入力（全角）" %>
      </div>
      <%# /著者名 %>
      <%# 出版社名 %>
      <div class="new-items">
        <div class="weight-bold-text">
          出版社名
          <span class="indispensable">必須</span>
        </div>
        <%=f.text_area :publisher, class:"item-text", id:"item-publisher", placeholder:"出版社名を入力（全角）" %>
      </div>
      <%# /出版社名 %>
      <%# 下部ボタン %>
      <div class="sell-btn-contents">
        <%= f.submit "変更する" ,class:"sell-btn" %>
        <%=link_to 'もどる', item_path(@item.id), class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
    <% end %>
  </div>
</div>

app/views/items/index.html.erb
<%= render "shared/header" %>

<div class='main'>
  <% if user_signed_in? %>
    <%# 商品名検索 %>
    <div class="item-search">
      <div class='item-search-title'>商品検索</div>
      <%= search_form_for @q, url: search_items_path, class:"search-input-form" do |f| %>
        <%= f.label :name_cont, '商品名', class:"search-input-name" %>
        <%= f.search_field :name_cont, class:"search-input-space" %>
        <%= f.label :lecture_cont, '講義名', class:"search-input-lecture" %>
        <%= f.search_field :lecture_cont, class:"search-input-space", placeholder:"全角で入力してください" %>
        <%= f.label :teacher_cont, '先生名', class:"search-input-teacher" %>
        <%= f.search_field :teacher_cont, class:"search-input-space", placeholder:"全角で入力してください" %>
        <%= f.submit '検索', class:"search-btn"%>
      <% end %>
    </div>
    <%# /商品名検索 %>
    <%# 商品一覧表示 %>
    <div class='item-contents'>
      <h2 class='title'>出品商品一覧</h2>
      <ul class='item-lists'>
        <% if @items[0] != nil %>
          <% @items.each do |item| %>
            <li class='list'>
              <%=link_to item_path(item.id) do %>
                <div class='item-img-content'>
                  <%= image_tag item.image, class: "item-img" %>
                  <% if item.order.present? %>
                    <div class='sold-out'>
                      <span>Sold Out!!</span>
                    </div>
                  <%end%>
                </div>
                <div class='item-info'>
                  <h3 class='item-name'>
                    <%= item.name %>
                  </h3>
                  <div class='item-info-sub'>
                    <span><%= item.price.to_s(:delimited) %>円
                    <br><%= item.user.university.name %>
                    <br><%= item.year_period.name %>
                    <br><%= item.lecture %>
                    <br><%= item.teacher %></span>
                  </div>
                </div>
              <% end %>
            </li>
          <% end %>
        <% else %>
          <div class='item-no-message'>
            現在出品中の商品はありません
          </div>
        <% end %>
      </ul>
    </div>
    <%# /商品一覧表示 %>
  <% else %>
    <%# ロゴ拡大表示部分 %>
    <div class="logo">
      <%= link_to image_tag("secondhands-logo02.png", class: "secondhands-logo"), "/" %>
    </div>
    <%# /ロゴ拡大表示部分 %>

    <%# SECONDHANDSの特徴 %>
    <div class='feature-contents'>
    <h2 class='title'>
     SECONDHANDSの特徴
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <%= image_tag "secondhands-intro01.png", class:"list-pict" %>
        <h3 class='feature-list-tex'>
          簡単に出品・購入
        </h3>
        <p class='feature-list-description'>
          使い終わった教科書はすぐに出品！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "secondhands-intro02.png", class:"list-pict" %>
        <h3 class='feature-list-tex'>
          すぐに買い手が見つかる
        </h3>
        <p class='feature-list-description'>
          大学内で探すから売買が効率的！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "secondhands-intro03.png", class:"list-pict" %>
        <h3 class='feature-list-tex'>
          他の教科書を購入
        </h3>
        <p class='feature-list-description'>
          他の授業の教科書を購入して出費を削減！
        </p>
      </li>
    </ul>
    <%# /SECONDHANDSの特徴 %>
  <% end %>
</div>
<%# 出品ボタン %>
<%= link_to(new_item_path, class: 'purchase-btn') do %>
  出品する
<% end %>
<%# /出品ボタン %>
<%= render "shared/footer" %>

app/views/items/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('secondhands-logo.png', size: '180x70'), "/" %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品情報を入力</h2>
    <%= form_with model: @item, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
      <%# 商品画像 %>
      <div class="img-upload">
        <div class="weight-bold-text">
          商品画像
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id:"image"%>
        </div>
      </div>
      <%# /商品画像 %>
      <%# 商品名 %>
      <div class="new-items">
        <div class="weight-bold-text">
          商品名
          <span class="indispensable">必須</span>
        </div>
        <%=f.text_area :name, class:"item-text", id:"item-name", placeholder:"商品名を入力" %>
      </div>
      <%# /商品名 %>
      <%# 商品価格 %>
      <div class="sell-price">
        <div class="weight-bold-text">
          商品価格
          <span class="indispensable">必須</span>
          <p>※送料は出品者負担になります</p>
        </div>
        <div class="price-space">
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"半角数字で入力" %>
        </div>
      </div>
      <%# /商品価格 %>
      <%# 年度・受講期 %>
      <div class="new-items">
        <div class="weight-bold-text">
          年度・受講期
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:year_period_id, YearPeriod.all, :id, :name, {}, {class:"active-select", id:"item-year-period"}) %>
      </div>
      <%# /年度・受講期 %>
      <%# 講義名 %>
      <div class="new-items">
        <div class="weight-bold-text">
          講義名
          <span class="indispensable">必須</span>
        </div>
        <%=f.text_area :lecture, class:"item-text", id:"item-lecture", placeholder:"講義名を入力（全角）" %>
      </div>
      <%# /講義名 %>
      <%# 先生名 %>
      <div class="new-items">
        <div class="weight-bold-text">
          先生名
          <span class="indispensable">必須</span>
        </div>
        <%=f.text_area :teacher, class:"item-text", id:"item-teacher", placeholder:"先生の氏名を入力（全角）" %>
      </div>
      <%# /先生名 %>
      <%# 商品の状態 %>
      <div class="new-items">
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:sales_status_id, SalesStatus.all, :id, :name, {}, {class:"active-select", id:"item-seles-status"}) %>
      </div>
      <%# /商品の状態 %>
      <%# 発送までの日数 %>
      <div class="new-items">
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:scheduled_delivery_id, ScheduledDelivery.all, :id, :name, {}, {class:"active-select", id:"item-scheduled-delivery"}) %>
      </div>
      <%# /発送までの日数 %>
      <%# 著者名 %>
      <div class="new-items">
        <div class="weight-bold-text">
          著者名
          <span class="indispensable">必須</span>
        </div>
        <%=f.text_area :author, class:"item-text", id:"item-autor", placeholder:"著者名を入力（全角）" %>
      </div>
      <%# /著者名 %>
      <%# 出版社名 %>
      <div class="new-items">
        <div class="weight-bold-text">
          出版社名
          <span class="indispensable">必須</span>
        </div>
        <%=f.text_area :publisher, class:"item-text", id:"item-publisher", placeholder:"出版社名を入力（全角）" %>
      </div>
      <%# /出版社名 %>
      <%# 下部ボタン %>
      <div class="sell-btn-contents">
        <%= f.submit "出品する" ,class:"sell-btn" %>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
    <% end %>
  </div>
</div>

app/views/items/search.html.erb
<%= render "shared/header" %>

<div class='main'>
  <%# 商品名検索 %>
  <div class="item-search">
    <div class='item-search-title'>商品検索</div>
    <%= search_form_for @q, url: search_items_path, class:"search-input-form" do |f| %>
      <%= f.label :name_cont, '商品名', class:"search-input-name" %>
      <%= f.search_field :name_cont, class:"search-input-space" %>
      <%= f.label :lecture_cont, '講義名', class:"search-input-lecture" %>
      <%= f.search_field :lecture_cont, class:"search-input-space", placeholder:"全角で入力してください" %>
      <%= f.label :teacher_cont, '先生名', class:"search-input-teacher" %>
      <%= f.search_field :teacher_cont, class:"search-input-space", placeholder:"全角で入力してください" %>
      <%= f.submit '検索', class:"search-btn"%>
    <% end %>
  </div>
  <%# /商品名検索 %>
  <%# 商品一覧表示 %>
  <div class='item-contents'>
    <h2 class='title'>検索結果一覧</h2>
    <ul class='item-lists'>
      <% if @results[0] != nil %>
        <% @results.each do |item| %>
          <li class='list'>
            <%=link_to item_path(item.id) do %>
              <div class='item-img-content'>
                <%= image_tag item.image, class: "item-img" %>
                <% if item.order.present? %>
                  <div class='sold-out'>
                    <span>Sold Out!!</span>
                  </div>
                <%end%>
              </div>
              <div class='item-info'>
                <h3 class='item-name'>
                  <%= item.name %>
                </h3>
                <div class='item-info-sub'>
                  <span><%= item.price.to_s(:delimited) %>円
                  <br><%= item.user.university.name %>
                  <br><%= item.year_period.name %>
                  <br><%= item.lecture %>
                  <br><%= item.teacher %></span>
                </div>
              </div>
            <% end %>
          </li>
        <% end %>
      <% else %>
        <div class='item-no-message'>
          検索結果に一致する商品はありません
        </div>
      <% end %>
    </ul>
  </div>
  <%# /商品一覧表示 %>
</div>

<%= render "shared/footer" %>

app/views/items/show.html.erb
<%= render "shared/second-header" %>

<%# 商品の詳細 %>
<div class="item-show">
  <div class="item-box">
    <div class="item-main-info">
      <%= image_tag @item.image, class:"item-box-img" %>
      <% if @item.order.present? %>
        <div class='sold-out-show'>
          <span>Sold Out!!</span>
        </div>
      <%end%>
      <div class="item-name-price">
        <span class="show-indispensable">商品名</span>
        <div class="item-name">
          <%= @item.name %>
        </div>
        <span class="show-indispensable">販売価格</span>
        <div class="item-price">
          <%= @item.price.to_s(:delimited) %>円
        </div>
        <% if user_signed_in? && @item.order == nil %>
          <% if current_user.id != @item.user_id %>
            <%= link_to "購入画面に進む", item_orders_path(@item.id), method: :get, class:"item-orange-btn"%>
          <% end %>
        <% end %>
      </div>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">大学名</th>
          <td class="detail-value"><%= @item.user.university.name%></td>
        </tr>
        <tr>
          <th class="detail-item">年度・受講期</th>
          <td class="detail-value"><%= @item.year_period.name%></td>
        </tr>
        <tr>
          <th class="detail-item">講義名</th>
          <td class="detail-value"><%= @item.lecture%></td>
        </tr>
        <tr>
          <th class="detail-item">先生名</th>
          <td class="detail-value"><%= @item.teacher%></td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= @item.sales_status.name%></td>
        </tr>
        <tr>
          <th class="detail-item">発送までの日数</th>
          <td class="detail-value"><%= @item.scheduled_delivery.name%></td>
        </tr>
        <tr>
          <th class="detail-item">著者名</th>
          <td class="detail-value"><%= @item.author%></td>
        </tr>
        <tr>
          <th class="detail-item">出版社名</th>
          <td class="detail-value"><%= @item.publisher%></td>
        </tr>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @item.user.nickname%></td>
        </tr>
      </tbody>
    </table>
    <% if user_signed_in? && @item.order == nil %>
      <% if current_user.id == @item.user_id %>
        <%= link_to "商品の編集", edit_item_path(@item.id),method: :get, class: "item-red-btn" %>
        <p class="or-text">or</p>
        <%= link_to "削除", item_path(@item.id), method: :delete, class:"item-destroy" %>
      <% end %>
    <%end%>
  </div>
</div>
<%# /商品の詳細 %>
<%= render "shared/second-footer"%>